### ISSUE TITLE
/run/loaddefault: No such file or directory

### ISSUE THREAD

**Issue by the-jojo-jj** [immauss/openvas#129]
root@afe61bb316c3:/scripts# pwd ; ./gvmd.sh 
/scripts
cat: /run/loaddefault: No such file or directory
root@afe61bb316c3:/scripts#

**Comment by immauss** [comment]
I'm going to a need a little more context to help out here. 

BUT . . . . . 

That's not a script you should be trying to run by hand. It used to started gvmd in a multi container environment. With that error, I'm guessing you are trying to run it in a single container, which is why that file does not exist. It is created on a shared volume, allowing the gvmd and postgresql containers to pass startup data. 

-Scott

**Comment by the-jojo-jj** [comment]
Yes, I want to add —max-ips-per-target=, and want to debug manually, because after committing and restarting still doesn’t work.

Thanks for your time and effort @immauss

**Comment by immauss** [comment]
Ah! OK ... Two things.

1: If you are using the single container, you'll need to make your changes to "single.sh" not gvmd.sh. 

2: You gave me an idea for another addition/upgrade.  I'm going to add an argument. GVMD_ARGS. If it exists, it will be tacked on to the gvmd command at start time making it easier to add things like this. 


Thanks,
-Scott

**Comment by the-jojo-jj** [comment]
Nice, You’ve got me!
anyway, where is the best place to add argument —max-ips-per-target? 
I’ve tried at single.sh, but after committed and restart makes can’t login.

thanks in advance.

**Comment by immauss** [comment]
It should be in single.sh .... 

If you are having trouble logging in, make sure gvmd is still running and if not, check the logs for any errors about your added option. 

It should be on line 200 .... 

If you pull the image pushed up yesterday, there is now an option "GVMD_ARGS". 

it "Should" work. 
I've only been able to test that it doesn't fail horribly if you **don't** put anything in the option.   :)

If you are able to put your option in that arg and it works out, please let me know. 

Thanks,
-Scott
