### ISSUE TITLE
gvmd.sock does not exist

### ISSUE THREAD

**Issue by tpaiii3** [immauss/openvas#135]
I am using python-gvm for automation with the docker image but while establishing connection it fails saying "could not find /var/run/gvmd.sock"
The file doesn't exist in this folder, also checked other folder /var/run etc. Couldn't find it anywhere.

**Comment by immauss** [comment]
Yes. This was by design. I had a ton of problems with the container and sockets, and in preparation for moving everything into separate containers, I switched the communication for to gvmd to a TCP socket. If you are using scripts, you'll need to have them use the "tls" option.

example:

gvm-script --gmp-password admin --gmp-username admin tls ./scantest.py


Thanks,
Scott
