### ISSUE TITLE
[BUG] Scanning is interrupted

### ISSUE THREAD

**Issue by fad2000** [immauss/openvas#285]
Hi Scott, need help
Installed immous in docker. Docker is running on a virtual machine running Almalinux.

 Virtualization: kvm
Operating System: AlmaLinux 9.4 (Seafoam Ocelot)
     CPE OS Name: cpe:/o:almalinux:almalinux:9::baseos
          Kernel: Linux 5.14.0-427.18.1.el9_4.x86_64
    Architecture: x86-64
 Hardware Vendor: Red Hat
  Hardware Model: KVM
Firmware Version: 0.5.1

When first used, scanning was interrupted with errors. Subsequent scan runs become impossible without restarting the container. After restarting the container, scanning starts but is interrupted again.
![fail4](https://github.com/immauss/openvas/assets/174675496/74da44a1-157b-4af4-be18-cd09a9926cbb)

Log in attachment (docker logs openvas).
[openvas.log](https://github.com/user-attachments/files/16093401/openvas.log)
Thanks.

**Comment by immauss** [comment]
Could you please provide details on how you started the container?

Command line? Docker compose file?

**Comment by immauss** [comment]
You have me at loss.

How did you set this up? Somewhere, there has to be more information about how the container is initially created. I could be missing something, but this will only start/stop an already created container. What I need is how the container was initially started.

-Scott
On Jul 4, 2024 at 14:34 +0200, fad2000 ***@***.***>, wrote:
		Could you please provide details on how you started the container? Command line? Docker compose file?
…
On Jul 4, 2024 at 06:37 +0200, fad2000 @.>, wrote: Assigned #285 to @immauss. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: @.>
it was:
systemctl daemon-reload
systemctl start openvas.service
systemctl enable openvas.service
with config openvas.service:
[Unit]
Description=MY DB (PG) docker container
Requires=docker.service
After=docker.service
[Service]
Restart=always
ExecStart=/usr/bin/docker start -a openvas
ExecStop=/usr/bin/docker stop -t 2 openvas
TimeoutSe
[Install]
WantedBy=multi-user.target

**Comment by fad2000** [comment]
oh.. I'm sorry, english is not my native ))
originally I did it like this:
docker volume create openvas
docker run --detach --publish 8080:9392 -e PASSWORD="mypass" --volume openvas:/data --name openvas immauss/openvas

**Comment by fad2000** [comment]
I think I found the problem. Not enough memory.

**Comment by immauss** [comment]
No worries.

Yes. The start looks good. That was my next question. You should give it at least 1 Gig of Memory if possible. It should work down to 512M though. The amount of memory needed though depends on the size of the scan you are running. I run my production scanners on 8Gig of memory. 

-Scott

**Comment by fad2000** [comment]
Yes, increased to 8, so far everything is going well.
Thanks.

**Comment by fad2000** [comment]
By the way, Scott, I want to thank you for a great product. Helped me a lot in my work!

**Comment by immauss** [comment]
Glad that fixed it, and thanks for the praise. Always happy to hear someone else finds my work helpful. 😉

-Scott
