### ISSUE TITLE
Configuring docker-compose with different user/password leaves default admin/admin user in place.

### ISSUE THREAD

**Issue by meichthys** [immauss/openvas#48]
It is probably not recommended to change the default admin/admin credentials in the docker-compose file, but that's what I did since I generally don't like to leave the username as 'admin'.

When changing the docker-compose file to use a different user/password, the default admin user is also setup with the default 'admin' password. I didn't realize this until i ran a scan against the OpenVAS host and received a severity score of 10.

![image](https://user-images.githubusercontent.com/10717998/122097646-e649e100-cddd-11eb-9ea6-ec52a3bd7495.png)

**Comment by immauss** [comment]
Well, that's not supposed to happen.

I'll try to look at this right away. 

Thanks!

**Comment by immauss** [comment]
Would you be willing to share the docker-compose.yml ?

**Comment by immauss** [comment]
Never mind ... I know what is happening. 
And it's something I realized a while ago, but some how lost track of it. 
The default database that is part of the image, to help get to a useable conatiner faster,  has the admin user created with the admin password. 
Unfortunately, I don't think it will be possible to remove the admin account, because it gets set as the feed owner. So I think what I will do is create a ludicrous password and assign it to the admin user on  first start if someone creates thier own user name via environment variables. (via compose or otherwise.) But you are right, having them set in the compose means anyone that can find the compose.yml will be able to see the password, and there may be other implications when restarting that I've not tested.

**Comment by meichthys** [comment]
I could be wrong, but i think the new user i created was set to be the feed owner (when i tried to delete my new user it said it could not be deleted because it was the feed owner.), so perhaps this would allow us to delete the admin user (?).

Also, I was able to remove the following two lines from the docker compose file after the first run and it seems to work fine. This way i don't need to leave my credentials in the `docker_compose.yaml` file which could be snooped on more easily.

```
      - "PASSWORD=my_password" # This should be changed asap after logging in via the web interface
      - "USERNAME=my_username" # This should be changed asap after logging in via the web interface
```

**Comment by immauss** [comment]
Hmmm ... you're right ... I did make a newly created user the feed owner. So ... the right thing to do would be delete the admin user if there is a request for newly created user. 
OK ... let me see if I can work that in. 

Thanks,
-Scott

**Comment by immauss** [comment]
OK ... I've added to the code base. 
It should be in my next release this week. 

-Scott

**Comment by immauss** [comment]
It's there. I've tested and it should be working. The admin user gets deleted now if you specify a different user. 
Though if you do this via compose, when you restart the container with those options, it will likely cause a problem since the admin account won't exist and the new user does exist. No easy way around this execept to say ... "Don't do that. " :)

**Comment by meichthys** [comment]
I could be doing something wrong, but i can't seem to login with the latest image when i use a custom user/pass:

DockerCompose:
```
      - PASSWORD=ChangeMeFast # Remove after first boot & change password via gui
      - USERNAME=openvasadmin # Remove after first boot
```

From the Logs:
![image](https://user-images.githubusercontent.com/10717998/124606177-9ee1ce00-de3a-11eb-9eee-e868ef2eb17e.png)

**Comment by csayre** [comment]
I am having an issue logging in with the latest version too. The defaults in the docker-compose file. 
```
- PASSWORD=admin # Remove after first boot & change password via gui
- USERNAME=admin # Remove after first boot
```

**Comment by immauss** [comment]
Tested latest today and worked fine for me. If you are still having problems, please open a new issue with no details including any relevant logs. 

Thanks,
Sxott
